const mongoose = require('mongoose');

const followUpSchema = new mongoose.Schema({
    leadId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Lead',
        required: true
    },
    managerId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Manager',
        required: true
    },
    type: {
        type: String,
        enum: ['call', 'email', 'meeting', 'test_drive', 'documentation', 'other'],
        required: true
    },
    dueDate: {
        type: Date,
        required: true
    },
    status: {
        type: String,
        enum: ['pending', 'completed', 'cancelled', 'overdue'],
        default: 'pending'
    },
    priority: {
        type: String,
        enum: ['low', 'medium', 'high', 'urgent'],
        default: 'medium'
    },
    comments: String,
    completedAt: Date,
    completedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Manager'
    },
    outcome: String,
    reminderSent: {
        type: Boolean,
        default: false
    },
    reminderSentAt: Date,
    autoGenerated: {
        type: Boolean,
        default: false
    },
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Manager'
    },
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
});

// Update timestamp
followUpSchema.pre('save', function (next) {
    this.updatedAt = Date.now();

    // Update status to overdue if past due date
    if (this.status === 'pending' && this.dueDate < new Date()) {
        this.status = 'overdue';
    }

    next();
});

// Index for efficient queries
followUpSchema.index({ managerId: 1, status: 1, dueDate: 1 });
followUpSchema.index({ leadId: 1 });

module.exports = mongoose.model('FollowUp', followUpSchema);

